export const ADD_REMINDER = 'ADD_REMINDER';
export const ADD_REMINDER_STARTED = 'ADD_REMINDER_STARTED';
export const ADD_REMINDER_FAILURE = 'ADD_REMINDER_FAILURE';

export const DELETE_REMINDER = 'DELETE_REMINDER';
export const DELETE_REMINDER_STARTED = 'DELETE_REMINDER_STARTED';
export const DELETE_REMINDER_FAILURE = 'DELETE_REMINDER_FAILURE';
