export const ADD_REMINDER = 'ADD_REMINDER';
export const ADD_REMINDER_STARTED = 'ADD_REMINDER_STARTED';
export const ADD_REMINDER_FAILURE = 'ADD_REMINDER_FAILURE';

export const DELETE_REMINDER = 'DELETE_REMINDER';
export const DELETE_REMINDER_STARTED = 'DELETE_REMINDER_STARTED';
export const DELETE_REMINDER_FAILURE = 'DELETE_REMINDER_FAILURE';

export const EDIT_REMINDER = 'EDIT_REMINDER';
export const EDIT_REMINDER_STARTED = 'EDIT_REMINDER_STARTED';
export const EDIT_REMINDER_FAILURE = 'EDIT_REMINDER_FAILURE';

export const GET_FORECAST = 'GET_FORECAST';
export const GET_FORECAST_STARTED = 'GET_FORECAST_STARTED';
export const GET_FORECAST_FAILURE = 'GET_FORECAST_FAILURE';
